### ISSUE TITLE
Enable 1-finger scrolling on mobile

### ISSUE THREAD

**Issue by asooge** [sei-uxdi-collab/work_from_roam-client#11]
Currently, on a mobile device map says:

"Use two fingers to move the map"

from google maps api: https://developers.google.com/maps/documentation/javascript/interaction

For mobile web apps:
Use two fingers to move the map. Note: You can use one finger to pan/drag the map, if the gestureHandling property is set to greedy.

**Comment by GMorse19** [comment]
Well done.
