### ISSUE TITLE
Add TopRated Info cards

### ISSUE THREAD

**Issue by reginapizza** [sei-uxdi-collab/work_from_roam-client#141]
Need to add TopRated cards into the header, according to figma drawings 
<img width="407" alt="Screen Shot 2020-04-18 at 11 31 56 PM" src="https://user-images.githubusercontent.com/50851526/79678778-d5e3a980-81cc-11ea-8e1f-c777720dbd60.png">

**Comment by reginapizza** [comment]
Anyone know how I might go about displaying the bars for wifi quality, seat comfort, etc? (also do we even have a seat comfort rating?)

**Comment by GMorse19** [comment]
We do not have a 'seat comfort' rating, yet. We do have a 'seating' field, but I believe that was originally just for amount of seating. Not sure if comfort and amount are supposed to be the same. I think the UX team is refining/finalizing some of these fields.
