### ISSUE TITLE
Button misplaced on WorkSpace.js 'first review' card.

### ISSUE THREAD

**Issue by GMorse19** [sei-uxdi-collab/work_from_roam-client#168]
Seems like the hours can occasionally push the button off the card.
<img width="341" alt="Screen Shot 2020-05-06 at 9 23 37 PM" src="https://user-images.githubusercontent.com/54245791/81244818-6568c500-8fe1-11ea-8dcf-5279b1fe90ce.png">

**Comment by reginapizza** [comment]
I haven't seen this as an issue recently, so I'm assuming it's been fixed and we can close the issue? @yingsongsana ?
