### ISSUE TITLE
Make phone numbers clickable/"call"-able

### ISSUE THREAD

**Issue by reginapizza** [sei-uxdi-collab/work_from_roam-client#173]
I think it's expected with most apps, especially on mobile, that you can click on a phone number on the screen and be able to call it without having to copy and paste. In order to do this, we would just need the phone number attribute with the following example code: 

`<a href="tel:+1896706255135">Call me at +1-896-7062-55135</a>`  

However, the data we get back from the api is not in the proper format (currently coming back as a string with parenthesis and dashes, which is good for displaying but not good for using in the a tag).

**Comment by reginapizza** [comment]
@GMorse19 how are we getting the data from the google api? Is it already in the backend somewhere unformatted or should I try to make something on the frontend to unformat it?

**Comment by GMorse19** [comment]
We can change the format in the API if we want. If we do that, will we have to do a similar front end format change for displaying it in HTML? Just wondering if it's it worth doing if we still have to do some form of format change, but we can definitely change the data in the API.

**Comment by reginapizza** [comment]
All good, I figured out a frontend solution so no need to change anything on the backend. 

Solution: 
1. Create a new formatPhone function: 
```const formatPhone = function(phone) {
    return "tel:" + phone.replace(/[ ()\\s-]+/g, "")
  }```
2.) In jsx, have the href use the function defined above to change into desired format: 
```<a href={formatPhone(workplace.phone)}>{workplace.phone}</a>```
