### ISSUE TITLE
UX/UI Component: Workspace Detail View

### ISSUE THREAD

**Issue by chardbres** [sei-uxdi-collab/work_from_roam-client#43]
Detailed view of selected workspace:
1. List of user reviews
2. Button to add own reviews
3. Aggregate amenity ratings

**Comment by GMorse19** [comment]
I added the amenity fields and their ratings.

**Comment by GMorse19** [comment]
Was able to get reviews list working properly... somewhat. We probably want to reconfigure the workspace and review tables in the API. At the very least, any Yes/No questions should be attached to work_space and any rating style questions should be attached to reviews.
